# Generated by Django 4.1.6 on 2023-11-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_con_tact_phone_number_alter_con_tact_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_registration',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='sea_rch',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=4, null=True),
        ),
    ]
